package com.jlmillan.sudokumaster.ui.theme

import androidx.compose.ui.graphics.Color


val LightAqua = Color(0xFFDDEEF0)
val PaleBlue = Color(0xFFDCEFFB)
val WhiteSudoku = Color(0xFFFFFFFF)
val LavenderBlue = Color(0xFFDFE0EA)
val VeryPaleCyan = Color(0xFFDEEDF7)
val MintCream = Color(0xFFE0F1EB)
val PowderBlue = Color(0xFFDEF0EA)
val LightMint = Color(0xFFDDEFE7)
val LightSeafoam = Color(0xFFDAEDE7)
val VeryLightCyan = Color(0xFFDDEFFB)
val LighterBlack = Color(0xFF1A1C29)
val Grey = Color(0xFF797979)
val Black = Color(0xFF000000)
val TextBlack = Color(0xFF1A1C29)
val TextDescription = Color(0xFF797979)
val WhiteWithAlpha = Color(0x8080FFFFFF)
val BackgroundInput = Color(0xFFF3F3F3)
val PaleCyan = Color(0xFFA4DBE6)
val PaleSkyBlue = Color(0xFFA5DCE7)
val VeryLightBlue = Color(0xFFA5DAE6)
val LightCyan = Color(0xFFA7DCE7)
val PaleBlue2 = Color(0xFFA6DDE8)
val PowderBlue2 = Color(0xFFA6DBE7)
val AliceBlue = Color(0xFFF7FBFE)
val LightSkyBlue = Color(0xFFA7DCE5)
val PaleCyan2 = Color(0xFFA5DBE6)
val TitleColor = Color(0xFF1A1C29)
val EditTextBackgroundColor = Color(0XFFF3F3F3)